import { DatabaseSync } from 'node:sqlite'
import { resolve } from 'node:path'
import { writeFileSync } from 'node:fs'

const root = resolve(import.meta.dirname, '..')
const dbPath = resolve(root, 'pb_data/data.db')
const outputPath = resolve(root, 'pb_migrations/1784190320_seed_existing_snapshot.js')

const collections = [
  'users', '_superusers', 'factories', 'score_templates', 'orders',
  'quality_inspections', 'quality_5s_checks', 'monthly_output',
  'monthly_scores', 'incidents', 'review_meetings', 'kpi_logs',
]
const authSecretFields = new Set(['password', 'tokenKey'])
const authSystemFields = new Set(['created', 'updated', 'avatar'])

const db = new DatabaseSync(dbPath, { readOnly: true })

function quotedIdentifier(value) {
  return `"${String(value).replaceAll('"', '""')}"`
}

function exportCollection(name) {
  const columns = db.prepare(`PRAGMA table_info(${quotedIdentifier(name)})`).all()
  const selected = columns
    .map((column) => String(column.name))
    .filter((field) => !authSecretFields.has(field))
    .filter((field) => !(name === 'users' || name === '_superusers') || !authSystemFields.has(field))
  const types = Object.fromEntries(columns.map((column) => [String(column.name), String(column.type).toUpperCase()]))
  const sql = `SELECT ${selected.map(quotedIdentifier).join(', ')} FROM ${quotedIdentifier(name)} ORDER BY id`
  return db.prepare(sql).all().map((source) => {
    const row = {}
    for (const field of selected) {
      let value = source[field]
      if (types[field] === 'JSON' && typeof value === 'string') {
        try { value = JSON.parse(value) } catch { /* Keep malformed legacy JSON as text. */ }
      }
      if (types[field] === 'BOOLEAN') value = Boolean(value)
      row[field] = value
    }
    return row
  })
}

const snapshot = Object.fromEntries(collections.map((name) => [name, exportCollection(name)]))

const secretValues = []
for (const table of ['users', '_superusers']) {
  for (const row of db.prepare(`SELECT password, tokenKey FROM ${quotedIdentifier(table)}`).all()) {
    if (row.password) secretValues.push(String(row.password))
    if (row.tokenKey) secretValues.push(String(row.tokenKey))
  }
}
db.close()

const migration = `// Generated by scripts/exportSeedSnapshot.mjs.
// Contains approved business data and user metadata only.
// Existing password hashes, token keys, OTP, MFA and auth-session data are intentionally excluded.
const SNAPSHOT = ${JSON.stringify(snapshot, null, 2)}

function filterValue(value) {
  return JSON.stringify(String(value ?? ''))
}

function findById(app, collection, id) {
  if (!id) return null
  try { return app.findRecordById(collection, id) } catch { return null }
}

function findByField(app, collection, field, value) {
  if (!value) return null
  try { return app.findFirstRecordByFilter(collection, field + ' = ' + filterValue(value)) } catch { return null }
}

function applyFields(record, row, relations = {}) {
  for (const [field, original] of Object.entries(row)) {
    if (field === 'id') continue
    let value = original
    const relationMap = relations[field]
    if (relationMap && typeof value === 'string' && relationMap[value]) value = relationMap[value]
    record.set(field, value)
  }
}

function saveAuthRecords(app, collectionName, rows) {
  const collection = app.findCollectionByNameOrId(collectionName)
  const idMap = {}
  for (const row of rows) {
    let record = findById(app, collectionName, row.id) || findByField(app, collectionName, 'email', row.email)
    const isNew = !record
    if (!record) {
      record = new Record(collection)
      record.set('id', row.id)
      record.setPassword($security.randomString(48))
    }
    applyFields(record, row)
    app.save(record)
    idMap[row.id] = record.id
    if (isNew) console.log('Seeded locked auth account:', collectionName, row.email)
  }
  return idMap
}

function saveFactories(app, rows, userIds) {
  const collection = app.findCollectionByNameOrId('factories')
  const idMap = {}
  const nameCounts = {}
  const preexistingByName = {}
  for (const row of rows) nameCounts[row.name] = (nameCounts[row.name] || 0) + 1
  for (const row of rows) {
    if (nameCounts[row.name] === 1) preexistingByName[row.name] = findByField(app, 'factories', 'name', row.name)
  }
  for (const row of rows) {
    let record = findById(app, 'factories', row.id) || preexistingByName[row.name]
    if (!record) {
      record = new Record(collection)
      record.set('id', row.id)
    }
    applyFields(record, row, { created_by: userIds, status_updated_by: userIds })
    app.save(record)
    idMap[row.id] = record.id
  }
  return idMap
}

function saveTemplates(app, rows) {
  const collection = app.findCollectionByNameOrId('score_templates')
  const idMap = {}
  for (const row of rows) {
    let record = findById(app, 'score_templates', row.id)
    if (!record) {
      try {
        const filter = 'name = ' + filterValue(row.name) + ' && craft_filter = ' + filterValue(row.craft_filter)
        record = app.findFirstRecordByFilter('score_templates', filter)
      } catch { record = null }
    }
    if (!record) {
      record = new Record(collection)
      record.set('id', row.id)
    }
    applyFields(record, row)
    app.save(record)
    idMap[row.id] = record.id
  }
  return idMap
}

function mapScoreItems(items, templateIds) {
  if (!Array.isArray(items)) return items
  return items.map((item) => ({
    ...item,
    template_id: templateIds[item?.template_id] || item?.template_id,
  }))
}

function saveBusinessRecords(app, collectionName, rows, userIds, factoryIds, templateIds) {
  const collection = app.findCollectionByNameOrId(collectionName)
  const userRelations = {
    created_by: userIds, approved_by: userIds, submitted_by: userIds,
    flag_approved_by: userIds, flag_issued_by: userIds, summary_by: userIds, user: userIds,
  }
  for (const source of rows) {
    const row = { ...source }
    if (collectionName === 'monthly_scores') row.score_items = mapScoreItems(row.score_items, templateIds)
    let record = findById(app, collectionName, row.id)
    if (!record) {
      record = new Record(collection)
      record.set('id', row.id)
    }
    applyFields(record, row, { ...userRelations, factory: factoryIds })
    app.save(record)
  }
}

migrate((app) => {
  const userIds = saveAuthRecords(app, 'users', SNAPSHOT.users)
  saveAuthRecords(app, '_superusers', SNAPSHOT._superusers)
  const factoryIds = saveFactories(app, SNAPSHOT.factories, userIds)
  const templateIds = saveTemplates(app, SNAPSHOT.score_templates)
  for (const name of [
    'orders', 'quality_inspections', 'quality_5s_checks', 'monthly_output',
    'monthly_scores', 'incidents', 'review_meetings', 'kpi_logs',
  ]) {
    saveBusinessRecords(app, name, SNAPSHOT[name], userIds, factoryIds, templateIds)
  }
}, (app) => {
  for (const name of [
    'kpi_logs', 'review_meetings', 'incidents', 'monthly_scores', 'monthly_output',
    'quality_5s_checks', 'quality_inspections', 'orders', 'score_templates', 'factories',
    'users', '_superusers',
  ]) {
    for (const row of SNAPSHOT[name]) {
      const record = findById(app, name, row.id)
      if (record) app.delete(record)
    }
  }
})
`

for (const secret of secretValues) {
  if (secret.length >= 8 && migration.includes(secret)) {
    throw new Error('Refusing to write snapshot: an authentication secret was detected in generated output')
  }
}
if (/"(?:password|tokenKey)"\s*:/.test(migration)) {
  throw new Error('Refusing to write snapshot: a forbidden authentication field was detected')
}

writeFileSync(outputPath, migration, { encoding: 'utf8', mode: 0o600 })
console.log('Wrote sanitized seed migration:', outputPath)
for (const name of collections) console.log(`${name}: ${snapshot[name].length}`)
